build: Define list of libc feature test macros
_POSIX_C_SOURCE is needed since it uses kill() API
and as per [1] it need it, without this the build fails
particularly on musl systems with clang compiler

./git/src/http.c:394:3: error: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

[1] https://man7.org/linux/man-pages/man2/kill.2.html